image:
  repository: mkhnoori1/complete-devops-project
  tag: 44f394b
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false