image:
  repository: mkhnoori1/complete-devops-project
  tag: 36f5748
  pullPolicy: IfNotPrsent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false